### ISSUE TITLE
Symbol not found

### ISSUE THREAD

**Issue by bartonhammond** [ewrogers/hda-calendar#10]
First: thanks for making this!
```
[hyper-calendar](main)$ bun run dev
$ bun --hot run src/index.ts
Started server http://localhost:3000
  <-- GET /
  --> GET / 302 1ms
  <-- GET /events
dyld: lazy symbol binding failed: Symbol not found: _ucal_getTimeZoneOffsetFromLocal
  Referenced from: /Users/bartonhammond/.bun/bin/bun (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libicucore.A.dylib

dyld: Symbol not found: _ucal_getTimeZoneOffsetFromLocal
  Referenced from: /Users/bartonhammond/.bun/bin/bun (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libicucore.A.dylib

error: script "dev" exited with code 9 (SIGKILL)
```

**Comment by ewrogers** [comment]
That's super interesting, I wonder if it's related to being on macOS 12? That's not *that* old of a version but maybe a bug of Bun. I've only tested on 13.x (Ventura) and 14.x (Sonoma)

You can try posting on [Bun's issue page](https://github.com/oven-sh/bun/issues) since this seems like a much deeper issue than just JS code.

**Comment by bartonhammond** [comment]
Yeah it’s that my MacBook Pro can’t be up graded - looks like it’s time for
a new one

**Comment by ewrogers** [comment]
I can definitely recommend the 15" MacBook Air M2!
